[general]
BROWSER = "chrome"
ELEMENT_OUTPUT_LOG = "user_friendly"
DO_NOT_RESTART = true
SOFT_RESTART = false
[custom]
SITE = "https://fix-online.sbis.ru"
USER_LOGIN = "arobelidze"
USER_PASSWORD = "SMJ123"
SHEDULE_PAGE = "https://fix-online.sbis.ru/page/work-schedule-documents"
EMPLOYEE = "Аробелидзе Жанна"
REASON1 = "Иду на концерт"
REASON2 = "Участвую в выборах"
STAFF = "Бланк Бенуа"
TIME_FROM = "12:30"
TIME_TO = "15:15"
PLANS_PAGE = "https://fix-online.sbis.ru/page/plans"
PLANNING_OBJ = "Палм-Спрингс"
CUSTOMER = "Бланк Бенуа"
POINT_TYPE = "Пункт плана"
POINT_DESC = "Закрыть гештальт"
POINT_EXECUTOR = "Аробелидзе Жанна"
POINT_CUSTOMER = "Кюри Мария"